# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-12 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0002_auto_20180112_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secondary_market.Item'),
            preserve_default=False,
        ),
    ]
