# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0005_auto_20180112_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='exp_price',
            field=models.IntegerField(),
        ),
    ]
