# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-12 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0006_auto_20180112_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='event_date',
            new_name='expiry_date',
        ),
    ]
