# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-18 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0007_auto_20180112_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.TextField(blank=True, max_length=2000000, null=True)),
            ],
        ),
    ]
