# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-18 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0009_auto_20180218_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='confirmation',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
    ]
