# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-18 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0010_auto_20180218_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='confirmation',
            new_name='conf',
        ),
    ]
