# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-18 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0011_auto_20180218_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_text', models.TextField(blank=True, max_length=200000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
