# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0013_auto_20180309_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_completed',
            new_name='payment_in_completed',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_phone',
            field=models.TextField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancelled',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_out_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_phone',
            field=models.TextField(blank=True, max_length=9, null=True),
        ),
    ]
