# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0014_auto_20180309_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tstamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.TextField(blank=True, default='fa-certificate', max_length=50),
        ),
    ]
