# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0015_auto_20180309_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.TextField(blank=True, max_length=250, null=True)),
                ('subject', models.TextField(blank=True, max_length=250, null=True)),
                ('body', models.TextField(blank=True, max_length=25000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inVenmoHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_text', models.TextField(blank=True, max_length=200000, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='decay_price',
            new_name='decay_rate',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='exp_price',
            new_name='exec_price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='json_text',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(blank=True, default=9999),
        ),
        migrations.AddField(
            model_name='payment',
            name='byVenmo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipient',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='txid',
            field=models.ForeignKey(default='AABBCCDD', on_delete=django.db.models.deletion.CASCADE, to='secondary_market.Transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='txid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondary_market.Transaction'),
        ),
    ]
