# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0016_auto_20180309_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='tstamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
