# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0017_auto_20180309_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='buyer_phone',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller_phone',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
