# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-11 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0018_auto_20180309_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exec_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
