# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0020_auto_20180311_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='tstamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
