# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0021_auto_20180312_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pickup_location',
            field=models.TextField(blank=True, default='On-campus', max_length=500),
        ),
    ]
