# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0022_transaction_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 26, 15, 11, 17, 778226)),
        ),
    ]
