# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 04:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0023_auto_20180312_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 27, 4, 33, 53, 611610)),
        ),
    ]
