# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 04:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0025_auto_20180313_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 27, 4, 34, 32, 519867)),
        ),
    ]
